version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: react
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    container_name: react
    tty: true
